config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions' }
  devise_scope :user do
    get 'farm/sign_up', to: 'registrations#new', user: { user_type: 'farm' }
    get 'organization/sign_up', to: 'registrations#new', user: { user_type: 'organization' }
  end

  resources :farms, only: :show do
    resources :products
    resources :postings, only: [:index]
    resources :farm_pickup_days, only: [:index]
  end

  resources :products, only: [] do
    resources :postings, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :postings, only: [:show]

  resources :organizations, only: [] do
    resources :orders, only: [:index, :show, :new, :update]
    resources :organization_pickup_days, only: [:index]
    resources :order_history, only: [:index]
  end

  resources :order_items, only: [:index, :show, :create, :update, :destroy]

  root to: 'home#index'

end

app/views/navbars/_farm_nav.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'FarmToTable', root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Incoming Orders', farm_farm_pickup_days_path(current_user.role) %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Products<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to 'View Products', farm_products_path(current_user.role) %> </li>
            <li><%= link_to 'New Product', new_farm_product_path(current_user.role) %></li>
          </ul>
        </li>
        <li><%= link_to 'Postings', farm_postings_path(current_user.role) %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-user"></span> <%= current_user.name %><span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to 'Edit Account', edit_user_registration_path %></li>
            <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/navbars/_new_user_nav.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'FarmToTable', root_path, class: "navbar-brand" %>
    </div>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Sign In', new_user_session_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Sign Up<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to 'as a farm', farm_sign_up_path %></li>
            <li><%= link_to 'as an organization', organization_sign_up_path %></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/navbars/_organization_nav.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'FarmToTable', root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'View Listings', order_items_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Active Orders<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to 'By Order', organization_orders_path(current_user.role) %></li>
            <li><%= link_to 'By Pick-Up Date', organization_organization_pickup_days_path(current_user.role) %></li>
          </ul>
        </li>
        <li><%= link_to 'Order History', organization_order_history_index_path(current_user.role) %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Current Order', new_organization_order_path(current_user.role) %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-user"></span> <%= current_user.name %><span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to 'Edit Account', edit_user_registration_path %></li>
            <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>