config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions' }
  devise_scope :user do
    get 'farm/sign_up', to: 'registrations#new', user: { user_type: 'farm' }
    get 'organization/sign_up', to: 'registrations#new', user: { user_type: 'organization' }
  end

  resources :farms, only: :show do
    resources :products
    resources :postings, only: [:index]
    resources :farm_pickup_days, only: [:index]
  end

  resources :products, only: [] do
    resources :postings, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :postings, only: [:show]

  resources :organizations, only: [] do
    resources :orders, only: [:index, :show, :new, :update]
    resources :organization_pickup_days, only: [:index]
    resources :order_history, only: [:index]
  end

  resources :order_items, only: [:index, :show, :create, :update, :destroy]

  root to: 'home#index'

end

app/controllers/order_history_controller.rb
class OrderHistoryController < ApplicationController

  before_action :authenticate_user!

  def index
    @orders = current_user.role.orders.where(is_completed: true).order(:created_at)
  end

end

app/views/order_history/index.html.erb
<h3 class="page-heading">Order History</h3>
<table class="table table-striped history-table">
  <tr>
    <th>ORDER DATE</th>
    <th>FARMS</th>
  </tr>
  <% @orders.each do |order| %>
    <tr>
      <td><%= link_to format_order_date_short(order), organization_order_path(current_user.role, order) %></td>
      <td><%= order.farms.join(', ') %></td>
    </tr>
  <% end %>
</table>