config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions' }
  devise_scope :user do
    get 'farm/sign_up', to: 'registrations#new', user: { user_type: 'farm' }
    get 'organization/sign_up', to: 'registrations#new', user: { user_type: 'organization' }
  end

  resources :farms, only: :show do
    resources :products
    resources :postings, only: [:index]
    resources :farm_pickup_days, only: [:index]
  end

  resources :products, only: [] do
    resources :postings, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :postings, only: [:show]

  resources :organizations, only: [] do
    resources :orders, only: [:index, :show, :new, :update]
    resources :organization_pickup_days, only: [:index]
    resources :order_history, only: [:index]
  end

  resources :order_items, only: [:index, :show, :create, :update, :destroy]

  root to: 'home#index'

end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id                 :integer          not null, primary key
#  name               :string(255)
#  variety            :string(255)
#  description        :text
#  organic            :boolean
#  non_gmo            :boolean
#  no_spray           :boolean
#  low_spray          :boolean
#  farm_id            :integer
#  created_at         :datetime
#  updated_at         :datetime
#  default_price      :decimal(, )
#  default_unit       :string(255)
#  image_file_name    :string(255)
#  image_content_type :string(255)
#  image_file_size    :integer
#  image_updated_at   :datetime
#

class Product < ActiveRecord::Base

  include ActivePosting

  has_attached_file :image, styles: {
    thumb: '100x100>',
    square: '200x200#',
    medium: '300x300>'
  },
  default_url: "/images/:style/missing.png"

  belongs_to :farm
  has_many :postings
  has_many :order_items, through: :postings

  validates :name, presence: true
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_farm
  before_action :set_product, only: [:edit, :update, :destroy]

  def index
    @products = @farm.products.order(:name)
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = @farm.products.new(product_params)

    if @product.save
      redirect_to farm_products_path(@farm), notice: "#{@product.name} created"
    else
      render :new
    end
  end

  def update
    if @product.update(product_params)
      redirect_to farm_products_path(@farm), notice: "#{@product.name} updated"
    else
      render :edit
    end
  end

  def destroy
    name = @product.name
    @product.destroy
    redirect_to farm_products_path(@farm), alert: "#{name} deleted"
  end

  private

  def product_params
    params.require(:product).permit(:name, :variety, :image, :description, :organic, :default_price, :default_unit, :non_gmo, :no_spray, :low_spray)
  end

  def set_farm
    @farm = Farm.find(params[:farm_id])
  end

  def set_product
    @product = @farm.products.find(params[:id])
  end

end

app/views/products/_form.html.erb
<%= form_for [@farm, @product] do |f| %>

  <%= render 'shared/errors', object: @product %>

  <div class="row">
    <div class="col-xs-5">
      <%= f.label :name, class: 'form-label' %>
    </div>
    <div class="col-xs-7">
      <%= f.text_field :name %>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-xs-5">
      <%= f.label :variety, class: 'form-label' %>
    </div>
    <div class="col-xs-7">
      <%= f.text_field :variety %>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-xs-5">
      <%= f.label :image, class: 'form-label' %>
    </div>
    <div class="col-xs-7">
      <%= f.file_field :image %>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-xs-5">
      <%= f.label :description, class: 'form-label' %>
    </div>
    <div class="col-xs-7">
      <%= f.text_area :description %>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-xs-5">
      <%= f.label :default_price, class: 'form-label' %>
    </div>
    <div class="col-xs-7">
      <%= f.text_field :default_price %>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-xs-5">
      <%= f.label :default_unit, class: 'form-label' %>
    </div>
    <div class="col-xs-7">
      <%= f.text_field :default_unit %>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-xs-5">
      <%= f.label :organic, class: 'form-label' %>
    </div>
    <div class="col-xs-7">
      <%= f.check_box :organic %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-5">
      <%= f.label :non_gmo, "Non-gmo", class: 'form-label' %>
    </div>
    <div class="col-xs-7">
      <%= f.check_box :non_gmo %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-5">
      <%= f.label :no_spray, "No-spray", class: 'form-label' %>
    </div>
    <div class="col-xs-7">
      <%= f.check_box :no_spray %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-5">
      <%= f.label :low_spray, "Low-spray", class: 'form-label' %>
    </div>
    <div class="col-xs-7">
      <%= f.check_box :low_spray %>
    </div>
  </div>
  <br>
  <div class="form-submit"><%= f.submit 'submit', class: 'btn btn-primary' %></div>
<% end %>

app/views/products/edit.html.erb
<h3 class="page-heading">Edit <%= @product.name %></h3>

<%= render 'form' %>

app/views/products/index.html.erb
<h3 class="page-heading">Products</h3>
<table class="table table-striped">
  <tr>
    <th>NAME</th>
    <th class="centered-table">VARIETY</th>
    <th class="centered-table">LAST POSTING</th>
    <th></th>
  </tr>
  <% @products.each do |product| %>
    <tr>
      <td><%= link_to product.name, farm_product_path(@farm, product) %></td>
      <td class="centered-table"><%= product.variety %></td>
      <td class="centered-table"><%= product.last_posting.present? ? product.last_posting.starting_date.to_formatted_s : '-' %></td>
      <td class="product-links">
        <button class="btn btn-primary"><%= link_to 'edit', edit_farm_product_path(@farm, product) %></button>
        <button class="btn btn-danger"><%= link_to 'delete', farm_product_path(@farm, product), method: :delete, data: {confirm: "Are you sure you want to delete #{product.name}?"} %></button>
        <button class="btn btn-success"><%= link_to 'create new posting', new_product_posting_path(product) %></button>
      </td>
    </tr>
  <% end %>
</table>

<button class="btn btn-success"><%= link_to 'create new product', new_farm_product_path(@farm) %></button>

app/views/products/new.html.erb
<h3 class="page-heading">New Product</h3>

<%= render 'form' %>

app/views/products/show.html.erb
<%= render 'shared/product_heading', product: @product %>

<h3 class="page-heading">Active Postings</h3>
<% if @product.active_postings.present? %>
  <%= render 'shared/postings_list', postings: @product.active_postings_by_date %>
<% else %>
  <p class="centered">there are no active postings for this product</p>
<% end %>

<h3 class="page-heading">Past Postings</h3>
<% if @product.inactive_postings.present? %>
  <%= render 'shared/postings_list', postings: @product.inactive_postings %>
<% else %>
  <p class="centered">there are no past postings for this product</p>
<% end %>

<button class="btn btn-primary"><%= link_to 'edit product', edit_farm_product_path(@product.farm, @product) %></button>
<button class="btn btn-success"><%= link_to 'create new posting', new_product_posting_path(@product) %></button>